name: CustomAdvancement
version: '${version}'
main: com.github.yufiriamazenta.customadvancement.CustomAdvancement
api-version: 1.17
load: POSTWORLD
authors: [ YufiriaMazenta ]
soft-depends: [ ItemsAdder, Oraxen, MythicMobs, NeigeItems ]
folia-supported: true
commands:
  customadvancement:
    aliases:
      - customadv
      - cadv
    permission: custom_advancement.command
permissions:
  custom_advancement.command:
    default: op
    children:
      custom_advancement.command.reload:
        default: op
      custom_advancement.command.grant:
        default: op
      custom_advancement.command.revoke:
        default: op