name: CustomAdvancement
version: '${version}'
main: com.github.yufiriamazenta.customadvancement.CustomAdvancement
api-version: 1.17
load: STARTUP
authors: [ YufiriaMazenta ]
folia-supported: true
commands:
  customadvancement:
    aliases:
      - customadv
    permission: customadvancement.command
permissions:
  customadvancement.command:
    default: op
